"""
Generate the engine parity fixture (formulation-lab-flow-spec.md §5.3.4).

Runs fixed ratio vectors through the authoritative engine.py and dumps the
scalar outputs + per-ingredient contributions to backend/tests/fixtures/
engine_parity.json. Two guards consume it:
  - backend/tests/test_engine_parity.py  (engine.py regression)
  - frontend/tests/engine_parity.test.ts (engine.ts must match the server)

Usage:  cd backend && python scripts/gen_engine_parity_fixture.py
"""

import json
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.models.formulation import (  # noqa: E402
    FormulationSimulateRequest,
    IngredientRatioInput,
)
from app.core.formulation.engine import simulate_formulation  # noqa: E402

FIXTURE_PATH = BACKEND_ROOT / "tests" / "fixtures" / "engine_parity.json"

VECTORS = [
    {
        "name": "golden_benchmark",
        "entity_type": "domestic",
        "ingredients": [("ashwagandha", 40.0), ("shilajit", 10.0), ("haridra", 30.0), ("pippali", 5.0), ("ghee", 15.0)],
    },
    {
        "name": "mere_admixture",
        "entity_type": "domestic",
        "ingredients": [("ashwagandha", 10.0), ("shilajit", 35.0), ("haridra", 25.0), ("pippali", 0.0), ("ghee", 30.0)],
    },
    {
        "name": "foreign_entity",
        "entity_type": "foreign",
        "ingredients": [("ashwagandha", 40.0), ("shilajit", 10.0), ("haridra", 30.0), ("pippali", 5.0), ("ghee", 15.0)],
    },
    {
        "name": "rasayana_matrix",
        "entity_type": "domestic",
        "ingredients": [("ashwagandha", 35.0), ("amla", 25.0), ("guduchi", 15.0), ("shilajit", 10.0), ("pippali", 5.0), ("ghee", 10.0)],
    },
    {
        "name": "critical_pippali",
        "entity_type": "domestic",
        "ingredients": [("methi", 25.0), ("guduchi", 20.0), ("neem", 20.0), ("tulsi", 15.0), ("ghee", 10.0), ("pippali", 10.0)],
    },
    {
        "name": "shallaki_joint",
        "entity_type": "domestic",
        "ingredients": [("shallaki", 35.0), ("haridra", 25.0), ("guggulu", 20.0), ("ashwagandha", 15.0), ("pippali", 5.0), ("ghee", 10.0), ("guduchi", 10.0)],
    },
    {
        "name": "budget_respiratory",
        "entity_type": "domestic",
        "ingredients": [("tulsi", 40.0), ("gokshura", 15.0), ("methi", 15.0), ("kantakari", 20.0), ("ghee", 10.0)],
    },
    {
        "name": "brahmi_ceiling_breach",
        "entity_type": "domestic",
        "ingredients": [("brahmi", 40.0), ("shankhpushpi", 30.0), ("ashwagandha", 15.0), ("pippali", 5.0), ("ghee", 10.0)],
    },
    {
        "name": "dantaka_arsha",
        "entity_type": "domestic",
        "ingredients": [("dantaka", 10.0), ("guduchi", 20.0), ("amla", 25.0), ("haritaki", 10.0), ("bibhitaki", 10.0), ("ghee", 10.0), ("pippali", 5.0), ("musta", 10.0)],
    },
    {
        "name": "unbalanced_partial",
        "entity_type": "domestic",
        "ingredients": [("ashwagandha", 30.0), ("haridra", 20.0), ("pippali", 5.0)],
    },
    {
        "name": "guggulu_royalty_trap",
        "entity_type": "domestic",
        "ingredients": [("guggulu", 30.0), ("haridra", 20.0), ("ashwagandha", 20.0), ("ghee", 25.0), ("pippali", 5.0)],
    },
]


def main() -> int:
    out = {"_comment": "Generated by scripts/gen_engine_parity_fixture.py — do not hand-edit.", "vectors": []}
    for v in VECTORS:
        req = FormulationSimulateRequest(
            title=v["name"],
            entity_type=v["entity_type"],
            ingredients=[
                IngredientRatioInput(herb_id=h, ratio=r) for h, r in v["ingredients"]
            ],
        )
        sim = simulate_formulation(req)
        out["vectors"].append({
            "name": v["name"],
            "entity_type": v["entity_type"],
            "ingredients": [{"herb_id": h, "ratio": r} for h, r in v["ingredients"]],
            "expected": {
                "total_ratio": sim.total_ratio,
                "is_balanced": sim.is_balanced,
                "chou_talalay_ci": sim.chou_talalay_ci,
                "sec_3e_status": sim.sec_3e_status,
                "bioavailability_multiplier": sim.bioavailability_multiplier,
                "anti_inflammatory_suppression": sim.anti_inflammatory_suppression,
                "ojas_power_score": sim.ojas_power_score,
                "tier": sim.tier.value if hasattr(sim.tier, "value") else sim.tier,
                "medicine_quality_score": sim.medicine_quality_score,
                "patentability_scope_score": sim.patentability_scope_score,
                "tkdl_concordance_score": sim.tkdl_concordance_score,
                "nba_abs_royalty_percentage": sim.nba_abs_royalty_percentage,
                "cost_per_unit": sim.cost_per_unit,
                "quadrant": sim.quadrant,
                "contributions": [
                    {
                        "herb_id": c.herb_id,
                        "layer": c.layer,
                        "quality_delta": c.quality_delta,
                        "ci_delta": c.ci_delta,
                        "patentability_delta": c.patentability_delta,
                        "royalty_delta": c.royalty_delta,
                        "cost_delta": c.cost_delta,
                        "state": c.state,
                        "fix_target": c.fix.target_ratio if c.fix else None,
                        "fix_action": c.fix.action_type if c.fix else None,
                    }
                    for c in sim.contributions
                ],
                "warning_ids": sorted(
                    f"{w['herb_id']}:{w['severity']}" for w in sim.patient_safety_warnings
                ),
            },
        })

    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(FIXTURE_PATH, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"Wrote {len(out['vectors'])} parity vectors to {FIXTURE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
