// Regenerates frontend/src/lib/formulation/defaults.ts from the backend
// catalog JSON (spec §8.4.4: defaults.ts is only a flagged offline fallback).
// Usage: node scripts/gen_offline_catalog.mjs   (run after backend data changes)
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..");

const botanicals = JSON.parse(readFileSync(resolve(root, "backend/data/formulation/botanicals.json"), "utf8"));
const presets = JSON.parse(readFileSync(resolve(root, "backend/data/formulation/presets.json"), "utf8"));

const out = `// AUTO-GENERATED by frontend/scripts/gen_offline_catalog.mjs from
// backend/data/formulation/{botanicals,presets}.json — DO NOT HAND-EDIT.
// This is the OFFLINE FALLBACK catalog only (spec §8.4.4): the page fetches
// /formulation-lab/herbs and /presets and treats them as authoritative;
// these copies render with a visible "static catalog" badge when the API is down.

import type { BotanicalItem, PresetFormulation } from "./types.ts";

export const OFFLINE_CATALOG = true as const;

export const DEFAULT_BOTANICALS: BotanicalItem[] = ${JSON.stringify(botanicals, null, 2)};

export const STARTER_PRESETS: PresetFormulation[] = ${JSON.stringify(presets, null, 2)};
`;

writeFileSync(resolve(root, "frontend/src/lib/formulation/defaults.ts"), out);
console.log(`Wrote defaults.ts: ${botanicals.length} herbs, ${presets.length} presets`);
