// AUTO-GENERATED by frontend/scripts/gen_offline_catalog.mjs from
// backend/data/formulation/{botanicals,presets}.json — DO NOT HAND-EDIT.
// This is the OFFLINE FALLBACK catalog only (spec §8.4.4): the page fetches
// /formulation-lab/herbs and /presets and treats them as authoritative;
// these copies render with a visible "static catalog" badge when the API is down.

import type { BotanicalItem, PresetFormulation } from "./types.ts";

export const OFFLINE_CATALOG = true as const;

export const DEFAULT_BOTANICALS: BotanicalItem[] = [
  {
    "id": "ashwagandha",
    "common_name": "Ashwagandha",
    "sanskrit_name": "अश्वगन्धा (Aśvagandhā)",
    "botanical_name": "Withania somnifera",
    "family": "Solanaceae",
    "part_used": "Dried Root",
    "marker_compound": "Withanolides / Withaferin-A",
    "standardized_percentage": "5.2% Withanolides",
    "category": "adaptogen",
    "single_agent_ed50": 40,
    "safety_ceiling_percent": 45,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsasthanam 1.1 / API Part-I Vol-I",
    "description": "Potent Balya (strength-promoting) and Rasayana adaptogen. Modulates HPA axis and suppresses cortisol."
  },
  {
    "id": "shilajit",
    "common_name": "Shodhit Shilajit",
    "sanskrit_name": "शिलाजतु (Śilājatu)",
    "botanical_name": "Asphaltum punjabianum",
    "family": "Mineral Pitch / Bitumen",
    "part_used": "Exudate / Purified Resin",
    "marker_compound": "Fulvic Acid & DBP",
    "standardized_percentage": "50.0% Fulvic Acid",
    "category": "mineral_resin",
    "single_agent_ed50": 25,
    "safety_ceiling_percent": 20,
    "is_mineral_resin": true,
    "is_threatened": false,
    "is_cultivated": false,
    "classical_reference": "Charaka Samhita Chikitsa 1.3 / Rasatarangini Taranga 22",
    "description": "Herbo-mineral catalyst. Cellular ATP rejuvenator and mitochondrial bio-energetic activator. High mineral sourcing scrutiny under BDA."
  },
  {
    "id": "haridra",
    "common_name": "Haridra (Turmeric)",
    "sanskrit_name": "हरिद्रा (Haridrā)",
    "botanical_name": "Curcuma longa",
    "family": "Zingiberaceae",
    "part_used": "Rhizome",
    "marker_compound": "Curcuminoids",
    "standardized_percentage": "95.0% Curcuminoids",
    "category": "anti_inflammatory",
    "single_agent_ed50": 50,
    "safety_ceiling_percent": 35,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Sutrasthanam 4 / API Part-I Vol-I",
    "description": "Varnya and Lekhana anti-inflammatory botanical. Suppresses NF-κB, TNF-α, and COX-2 cascades."
  },
  {
    "id": "pippali",
    "common_name": "Pippali (Long Pepper)",
    "sanskrit_name": "पिप्पली (Pippalī)",
    "botanical_name": "Piper longum",
    "family": "Piperaceae",
    "part_used": "Dried Fruit Spike",
    "marker_compound": "Piperine",
    "standardized_percentage": "98.0% Piperine",
    "category": "bio_enhancer",
    "single_agent_ed50": 10,
    "safety_ceiling_percent": 6,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsa 1.3 / Bhavaprakasha Nighantu",
    "description": "Prime Yogavāhī (bio-enhancer) and Deepana-Pachana catalyst. Downregulates CYP3A4 and P-glycoprotein to multiply systemic bioavailability by 2x-4x."
  },
  {
    "id": "ghee",
    "common_name": "Vedic Cow Ghrita",
    "sanskrit_name": "गोघृत (Goghṛta)",
    "botanical_name": "Clarified Cow Butter Liposomes",
    "family": "Lipid Vehicle / Anupana",
    "part_used": "A2 Cow Milk Lipid Fraction",
    "marker_compound": "Butyric Acid & CLA",
    "standardized_percentage": "99.5% Triglyceride Lipids",
    "category": "carrier",
    "single_agent_ed50": 80,
    "safety_ceiling_percent": 25,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Sushruta Samhita Sutrasthanam 45 / Charaka Sutra 27",
    "description": "Liposomal lipid carrier (Sneha Samskara). Facilitates crossing of the blood-brain barrier and enhances mucosal lymphatic transport."
  },
  {
    "id": "guduchi",
    "common_name": "Guduchi (Giloy)",
    "sanskrit_name": "गुडूची (Guḍūcī)",
    "botanical_name": "Tinospora cordifolia",
    "family": "Menispermaceae",
    "part_used": "Stem",
    "marker_compound": "Cordifolioside A / Berberine",
    "standardized_percentage": "3.5% Bitter Glycosides",
    "category": "digestive",
    "single_agent_ed50": 35,
    "safety_ceiling_percent": 25,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsasthanam 1.2 / API Part-I Vol-I",
    "description": "Amrita (nectar). Potent immunomodulator, Rasayana, and hepatoprotective shield that neutralizes mineral toxicity."
  },
  {
    "id": "brahmi",
    "common_name": "Brahmi",
    "sanskrit_name": "ब्राह्मी (Brāhmī)",
    "botanical_name": "Bacopa monnieri",
    "family": "Plantaginaceae",
    "part_used": "Whole Plant",
    "marker_compound": "Bacosides A & B",
    "standardized_percentage": "55.0% Bacosides",
    "category": "medhya",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 30,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Sharirasthanam 8 / API Part-I Vol-II",
    "description": "Medhya Rasayana for synaptic plasticity, acetylcholine transmission, and neuroprotection."
  },
  {
    "id": "shankhpushpi",
    "common_name": "Shankhpushpi",
    "sanskrit_name": "शङ्खपुष्पी (Śaṅkhapuṣpī)",
    "botanical_name": "Convolvulus pluricaulis",
    "family": "Convolvulaceae",
    "part_used": "Whole Plant",
    "marker_compound": "Scopoletin / Microphylic Acid",
    "standardized_percentage": "2.5% Alkaloids",
    "category": "medhya",
    "single_agent_ed50": 45,
    "safety_ceiling_percent": 35,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsa 1.3 / Bhavaprakasha Nighantu",
    "description": "Supreme Medhya botanical, pacifies Pitta and Vata, calms neuro-excitation and supports sleep."
  },
  {
    "id": "amla",
    "common_name": "Amalaki (Indian Gooseberry)",
    "sanskrit_name": "आमलकी (Āmalakī)",
    "botanical_name": "Phyllanthus emblica",
    "family": "Phyllanthaceae",
    "part_used": "Pericarp of Fruit",
    "marker_compound": "Emblicanin A & B / Gallic Acid",
    "standardized_percentage": "45.0% Tannins",
    "category": "digestive",
    "single_agent_ed50": 40,
    "safety_ceiling_percent": 40,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsasthanam 1.1 / API Part-I Vol-I",
    "description": "Vayasthapana (anti-aging) cornerstone of Chyawanprash. Rich in natural antioxidant polymers."
  },
  {
    "id": "guggulu",
    "common_name": "Shodhit Guggulu",
    "sanskrit_name": "गुग्गुलु (Guggulu)",
    "botanical_name": "Commiphora mukul",
    "family": "Burseraceae",
    "part_used": "Oleoresin",
    "marker_compound": "Guggulsterones E & Z",
    "standardized_percentage": "2.5% Guggulsterones",
    "category": "anti_inflammatory",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 25,
    "is_mineral_resin": true,
    "is_threatened": true,
    "is_cultivated": false,
    "classical_reference": "Sushruta Samhita Sutrasthanam 38 / Bhavaprakasha Nighantu",
    "description": "Deep-tissue penetrator (Srotoshodhaka). Lowers lipids, combats arthritic swelling. BDA threatened status."
  },
  {
    "id": "neem",
    "common_name": "Neem",
    "sanskrit_name": "निम्ब (Nimba)",
    "botanical_name": "Azadirachta indica",
    "family": "Meliaceae",
    "part_used": "Leaf",
    "marker_compound": "Nimbidin / Azadirachtin",
    "standardized_percentage": "2.0% Nimbidin",
    "category": "anti_inflammatory",
    "single_agent_ed50": 45,
    "safety_ceiling_percent": 20,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Sutrasthanam 4 / API Part-I Vol-I",
    "description": "Krimighna and Kutaghna blood-purifier. Standard TKDL anchor for dermatological and antipyretic prior art."
  },
  {
    "id": "shallaki",
    "common_name": "Shallaki (Boswellia)",
    "sanskrit_name": "शाल्लकी (Śalllakī)",
    "botanical_name": "Boswellia serrata",
    "family": "Burseraceae",
    "part_used": "Resinous Extract",
    "marker_compound": "Boswellic Acids (AKBA)",
    "standardized_percentage": "30.0% Boswellic Acids",
    "category": "anti_inflammatory",
    "single_agent_ed50": 35,
    "safety_ceiling_percent": 30,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Sushruta Samhita Sutrasthanam 45 / API Part-I Vol-I",
    "description": "5-LOX inhibitor yoga for Sandhivata. Modern standardization patents coexist with TKDL-documented guggulu yogas."
  },
  {
    "id": "yashti",
    "common_name": "Yashti (Licorice)",
    "sanskrit_name": "यष्टि (Yaṣṭi)",
    "botanical_name": "Glycyrrhiza glabra",
    "family": "Fabaceae",
    "part_used": "Stolon/Root",
    "marker_compound": "Glycyrrhizin",
    "standardized_percentage": "10.0-15.0% Glycyrrhizin",
    "category": "digestive",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 12,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsa 1.3 / API Part-I Vol-I",
    "description": "Vatahara demulcent. Above ceiling risk: pseudo-hyperaldosteronism with blood-pressure elevation."
  },
  {
    "id": "tulsi",
    "common_name": "Tulsi (Holy Basil)",
    "sanskrit_name": "तुलसी (Tulasī)",
    "botanical_name": "Ocimum sanctum",
    "family": "Lamiaceae",
    "part_used": "Leaf",
    "marker_compound": "Ursolic Acid / Eugenol",
    "standardized_percentage": "1.0% Ursolic Acid",
    "category": "adaptogen",
    "single_agent_ed50": 40,
    "safety_ceiling_percent": 25,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Vrindavana Chikitsa / API Part-II",
    "description": "Svasa (respiratory) adaptogen and antipyretic. TKDL-documented decoction uses block modern therapeutic patents."
  },
  {
    "id": "arjuna",
    "common_name": "Arjuna",
    "sanskrit_name": "अर्जुन (Arjuna)",
    "botanical_name": "Terminalia arjuna",
    "family": "Combretaceae",
    "part_used": "Bark",
    "marker_compound": "Arjunosit B / Beta-Sitosterol",
    "standardized_percentage": "2.0% Arjunosit B",
    "category": "adaptogen",
    "single_agent_ed50": 35,
    "safety_ceiling_percent": 30,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsa 28 (Hridya protocols)",
    "description": "Premier Hridya (cardiac) Rasayana bark; positive inotrope and endothelial support."
  },
  {
    "id": "methi",
    "common_name": "Methi (Fenugreek)",
    "sanskrit_name": "मेथी (Medhikā)",
    "botanical_name": "Trigonella foenum-graecum",
    "family": "Fabaceae",
    "part_used": "Seed",
    "marker_compound": "Furostanolic Saponins",
    "standardized_percentage": "20.0% Saponins",
    "category": "digestive",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 20,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Sutrasthanam 4 / API Part-I Vol-VIII",
    "description": "Prameha (sugar-balance) staple. TKDL blocked several 'novel use' patent applications at EPO/USPTO."
  },
  {
    "id": "dantaka",
    "common_name": "Dantaka (Leadwort)",
    "sanskrit_name": "दन्तक (Dantaka)",
    "botanical_name": "Plumbago zeylanica",
    "family": "Plumbaginaceae",
    "part_used": "Root",
    "marker_compound": "Plumbagin",
    "standardized_percentage": "0.1% Plumbagin",
    "category": "digestive",
    "single_agent_ed50": 20,
    "safety_ceiling_percent": 8,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Bhavaprakasha Nighantu (Dantaki) / API Part-I Vol-VIII",
    "description": "Deepana-Agneeja root for Arsha (piles) and Ayaskrita bhasma processes. Narrow therapeutic window."
  },
  {
    "id": "bilva",
    "common_name": "Bilva (Wood Apple)",
    "sanskrit_name": "बिल्व (Bilva)",
    "botanical_name": "Aegle marmelos",
    "family": "Rutaceae",
    "part_used": "Fruit Pulp",
    "marker_compound": "Aegeline / Marmin",
    "standardized_percentage": "1.0% Aegeline",
    "category": "digestive",
    "single_agent_ed50": 40,
    "safety_ceiling_percent": 25,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Bhavaprakasha Nighantu / API Part-I Vol-I",
    "description": "Grahani (bowel-bind) astringent fruit; classical Pitta accumulator with antimicrobial furanocoumarins."
  },
  {
    "id": "shatavari",
    "common_name": "Shatavari",
    "sanskrit_name": "शतावरी (Śatāvarī)",
    "botanical_name": "Asparagus racemosus",
    "family": "Asparagaceae",
    "part_used": "Tuberous Root",
    "marker_compound": "Shatavarins",
    "standardized_percentage": "2.0% Shatavarins",
    "category": "adaptogen",
    "single_agent_ed50": 35,
    "safety_ceiling_percent": 30,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsa 1.1 / API Part-I Vol-I",
    "description": "Brimhana (nourishing) adaptogen; galactagogue and female-reproductive Rasayana."
  },
  {
    "id": "gokshura",
    "common_name": "Gokshura (Puncture Vine)",
    "sanskrit_name": "गोक्षुर (Gokṣura)",
    "botanical_name": "Tribulus terrestris",
    "family": "Zygophyllaceae",
    "part_used": "Fruit",
    "marker_compound": "Terminolic Acid / Beta-Sitosterol",
    "standardized_percentage": "20.0% Saponins",
    "category": "digestive",
    "single_agent_ed50": 40,
    "safety_ceiling_percent": 25,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Sutrasthanam 4 / API Part-I Vol-VII",
    "description": "Mutra-vardhaka (urinary flow) renal tonic and Vataya Balya muscle support."
  },
  {
    "id": "punarnava",
    "common_name": "Punarnava",
    "sanskrit_name": "पुनर्नवा (Punarnava)",
    "botanical_name": "Boerhavia diffusa",
    "family": "Nyctaginaceae",
    "part_used": "Root",
    "marker_compound": "Punarnavine / Rotundin",
    "standardized_percentage": "1.0% Punarnavine",
    "category": "digestive",
    "single_agent_ed50": 35,
    "safety_ceiling_percent": 20,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsa 14 (Shothahara) / API Part-I Vol-I",
    "description": "Shothahara (anti-edema) rejuvenator of the kidneys; classical Jalaroga water-balance yoga."
  },
  {
    "id": "haritaki",
    "common_name": "Haritaki",
    "sanskrit_name": "हरীतकी (Harītakī)",
    "botanical_name": "Terminalia chebula",
    "family": "Combretaceae",
    "part_used": "Fruit",
    "marker_compound": "Chebulinic Acid",
    "standardized_percentage": "30.0% Tannins",
    "category": "digestive",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 20,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Chikitsa 4 / Bhavaprakasha Nighantu",
    "description": "Anulomana purgative; best of the three Triphala fruits for Vata and the eyes."
  },
  {
    "id": "bibhitaki",
    "common_name": "Bibhitaki",
    "sanskrit_name": "विभीतक (Vibhītaka)",
    "botanical_name": "Terminalia bellirica",
    "family": "Combretaceae",
    "part_used": "Fruit",
    "marker_compound": "Gallic / Ellagic Acid",
    "standardized_percentage": "25.0% Tannins",
    "category": "digestive",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 20,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Sutrasthanam 4 / API Part-I Vol-I",
    "description": "Kapha-pacifying member of Triphala; respiratory and Ayushya (longevity) astringent."
  },
  {
    "id": "musta",
    "common_name": "Musta (Nutgrass)",
    "sanskrit_name": "मुस्तक (Mustakā)",
    "botanical_name": "Cyperus rotundus",
    "family": "Cyperaceae",
    "part_used": "Rhizome",
    "marker_compound": "Cyperene / Cyperol",
    "standardized_percentage": "1.5% Essential Oil",
    "category": "digestive",
    "single_agent_ed50": 25,
    "safety_ceiling_percent": 15,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Bhavaprakasha Nighantu / Charaka Chikitsa 3 (Daha)",
    "description": "Daha (burning) and Jwara (fever) refrigerant rhizome; classical anti-diarrheal vehicle."
  },
  {
    "id": "kumari",
    "common_name": "Kumari (Aloe)",
    "sanskrit_name": "कुमारी (Kumārī)",
    "botanical_name": "Aloe barbadensis",
    "family": "Asphodelaceae",
    "part_used": "Leaf Juice",
    "marker_compound": "Barbaloin (Anthraquinones)",
    "standardized_percentage": "12.0% Acemannan Gel",
    "category": "digestive",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 15,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Charaka Samhita Sutrasthanam 4 / API Part-I Vol-I",
    "description": "Sheetala (cooling) Pitta sedative; Kumari ashta-churna anchors liver and menstrual yogas."
  },
  {
    "id": "vidari",
    "common_name": "Vidari",
    "sanskrit_name": "विदारी (Vidārī)",
    "botanical_name": "Descurainia sophia",
    "family": "Brassicaceae",
    "part_used": "Root",
    "marker_compound": "Pregnane Glycosides",
    "standardized_percentage": "1.0% Steroidal Saponins",
    "category": "adaptogen",
    "single_agent_ed50": 45,
    "safety_ceiling_percent": 25,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Bhavaprakasha Nighantu (Vidari) / API Part-I Vol-I",
    "description": "Brimhana nourishing root for emaciation and Pitta; the 'night jasmine' of the Rasayana chapters."
  },
  {
    "id": "ballataka",
    "common_name": "Ballataka (Wood Apple Gum)",
    "sanskrit_name": "बल्लाटक (Ballāṭaka)",
    "botanical_name": "Limonia acidissima",
    "family": "Rutaceae",
    "part_used": "Fruit / Gum",
    "marker_compound": "Feronia Gum Polysaccharides",
    "standardized_percentage": "10.0% Mucilage",
    "category": "digestive",
    "single_agent_ed50": 40,
    "safety_ceiling_percent": 20,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Bhavaprakasha Nighantu / API Part-I Vol-V",
    "description": "Grahani and hemorrhoidal astringent; classical Krimighna (parasitic) gut binder."
  },
  {
    "id": "kantakari",
    "common_name": "Kantikari (Solanum)",
    "sanskrit_name": "कण्टकारী (Kaṇṭakārī)",
    "botanical_name": "Solanum virginianum",
    "family": "Solanaceae",
    "part_used": "Root",
    "marker_compound": "Solasodine",
    "standardized_percentage": "0.5% Solasodine",
    "category": "digestive",
    "single_agent_ed50": 30,
    "safety_ceiling_percent": 15,
    "is_mineral_resin": false,
    "is_threatened": false,
    "is_cultivated": true,
    "classical_reference": "Dhanvantari Nighantu (Kantakari) / API Part-I Vol-VIII",
    "description": "Kasa (cough) and Shwasa respiratory bronchodilator root; paired with vasa in classical kvatha recipes."
  }
];

export const STARTER_PRESETS: PresetFormulation[] = [
  {
    "id": "rev_3_2_benchmark",
    "title": "Synergistic Ashwagandha-Shilajit-Curcumin Compound (Rev. 3.2)",
    "description": "Strong medicine, but TKDL reads as §3(p) prior art — add Guduchi 6% to drop below the 90 line.",
    "target_tier": "divya_rasayana",
    "ingredients": [
      {
        "herb_id": "ashwagandha",
        "ratio": 40
      },
      {
        "herb_id": "shilajit",
        "ratio": 10
      },
      {
        "herb_id": "haridra",
        "ratio": 30
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      },
      {
        "herb_id": "ghee",
        "ratio": 15
      }
    ],
    "baseline_ratios": {
      "ashwagandha": 40,
      "shilajit": 10,
      "haridra": 30,
      "pippali": 5,
      "ghee": 15
    },
    "computed": {
      "quality": 98,
      "ci": 0.57,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 92,
      "tier": "divya_rasayana",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "rasayana_matrix",
    "title": "Rejuvenative Rasayana Matrix",
    "description": "Complete five-layer yoga; Guduchi keeps TKDL under the §3(p) line but shilajit sits near its resin ceiling.",
    "target_tier": "siddha",
    "ingredients": [
      {
        "herb_id": "ashwagandha",
        "ratio": 35
      },
      {
        "herb_id": "amla",
        "ratio": 25
      },
      {
        "herb_id": "guduchi",
        "ratio": 15
      },
      {
        "herb_id": "shilajit",
        "ratio": 10
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      },
      {
        "herb_id": "ghee",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "ashwagandha": 35,
      "amla": 25,
      "guduchi": 15,
      "shilajit": 10,
      "pippali": 5,
      "ghee": 10
    },
    "computed": {
      "quality": 94,
      "ci": 0.63,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 83,
      "tier": "siddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "anti_inflammatory_catalyst",
    "title": "Anti-Inflammatory Haridra-Pippali Catalyst",
    "description": "Powerful COX-2/NF-κB yoga, but Haridra at 45% breaches the 35% safety ceiling and Guggulu pulls royalty to the 5% bracket.",
    "target_tier": "siddha",
    "ingredients": [
      {
        "herb_id": "haridra",
        "ratio": 45
      },
      {
        "herb_id": "guggulu",
        "ratio": 25
      },
      {
        "herb_id": "ashwagandha",
        "ratio": 15
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      },
      {
        "herb_id": "ghee",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "haridra": 45,
      "guggulu": 25,
      "ashwagandha": 15,
      "pippali": 5,
      "ghee": 10
    },
    "computed": {
      "quality": 99,
      "ci": 0.71,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "siddha",
      "nba_abs_royalty_percentage": 5,
      "cost_per_unit": 76.7
    }
  },
  {
    "id": "medhya_neuro_enhancer",
    "title": "Medhya Cognitive Neuro-Enhancer",
    "description": "Nootropic depth, but Brahmi at 40% exceeds the 25% vagal ceiling — reduce to 25% before examination.",
    "target_tier": "vriddha",
    "ingredients": [
      {
        "herb_id": "brahmi",
        "ratio": 40
      },
      {
        "herb_id": "shankhpushpi",
        "ratio": 30
      },
      {
        "herb_id": "ashwagandha",
        "ratio": 15
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      },
      {
        "herb_id": "ghee",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "brahmi": 40,
      "shankhpushpi": 30,
      "ashwagandha": 15,
      "pippali": 5,
      "ghee": 10
    },
    "computed": {
      "quality": 78,
      "ci": 0.71,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "vriddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "shwasa_cheap_kwath",
    "title": "Svasa Respiratory Decoction (Budget Cut)",
    "description": "Cheap to make and safety-clean, but no bio-enhancer and no hero adaptogen — the IPO reads it as a mere admixture (§3(e)).",
    "target_tier": "bala",
    "ingredients": [
      {
        "herb_id": "tulsi",
        "ratio": 25
      },
      {
        "herb_id": "gokshura",
        "ratio": 20
      },
      {
        "herb_id": "methi",
        "ratio": 15
      },
      {
        "herb_id": "kantakari",
        "ratio": 15
      },
      {
        "herb_id": "ghee",
        "ratio": 15
      },
      {
        "herb_id": "musta",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "tulsi": 25,
      "gokshura": 20,
      "methi": 15,
      "kantakari": 15,
      "ghee": 15,
      "musta": 10
    },
    "computed": {
      "quality": 55,
      "ci": 1.21,
      "sec_3e_status": "REJECTED",
      "tkdl_concordance_score": 58,
      "tier": "bala",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "prameha_fenugreek_quatro",
    "title": "Prameha Sugar-Balance Quattro",
    "description": "Cleared §3(e) at CI 0.57, but Pippali at 10% breaches the 6% gastric ceiling — a CRITICAL patient-safety objection.",
    "target_tier": "vriddha",
    "ingredients": [
      {
        "herb_id": "methi",
        "ratio": 25
      },
      {
        "herb_id": "guduchi",
        "ratio": 20
      },
      {
        "herb_id": "neem",
        "ratio": 20
      },
      {
        "herb_id": "tulsi",
        "ratio": 15
      },
      {
        "herb_id": "ghee",
        "ratio": 10
      },
      {
        "herb_id": "pippali",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "methi": 25,
      "guduchi": 20,
      "neem": 20,
      "tulsi": 15,
      "ghee": 10,
      "pippali": 10
    },
    "computed": {
      "quality": 76,
      "ci": 0.75,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "vriddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "sandhivata_shallaki_yoga",
    "title": "Sandhivata Boswellia-Joint Yoga",
    "description": "High 5-LOX anti-inflammatory load, but Shallaki at 35% sits above its 30% API ceiling — trim before filing.",
    "target_tier": "divya_rasayana",
    "ingredients": [
      {
        "herb_id": "shallaki",
        "ratio": 35
      },
      {
        "herb_id": "haridra",
        "ratio": 25
      },
      {
        "herb_id": "guggulu",
        "ratio": 20
      },
      {
        "herb_id": "ashwagandha",
        "ratio": 15
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      },
      {
        "herb_id": "ghee",
        "ratio": 10
      },
      {
        "herb_id": "guduchi",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "shallaki": 35,
      "haridra": 25,
      "guggulu": 20,
      "ashwagandha": 15,
      "pippali": 5,
      "ghee": 10,
      "guduchi": 10
    },
    "computed": {
      "quality": 97,
      "ci": 0.63,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "divya_rasayana",
      "nba_abs_royalty_percentage": 3.5,
      "cost_per_unit": 74.6
    }
  },
  {
    "id": "medoroga_guggulu_lean",
    "title": "Medoroga Lipid-Control Guggulu Build",
    "description": "Patent-strong synergy, but Guggulu at 30% is a threatened resin: 5% royalty bracket plus a dermatitis ceiling breach.",
    "target_tier": "divya_rasayana",
    "ingredients": [
      {
        "herb_id": "guggulu",
        "ratio": 30
      },
      {
        "herb_id": "haridra",
        "ratio": 20
      },
      {
        "herb_id": "ashwagandha",
        "ratio": 20
      },
      {
        "herb_id": "ghee",
        "ratio": 25
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      }
    ],
    "baseline_ratios": {
      "guggulu": 30,
      "haridra": 20,
      "ashwagandha": 20,
      "ghee": 25,
      "pippali": 5
    },
    "computed": {
      "quality": 94,
      "ci": 0.57,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "divya_rasayana",
      "nba_abs_royalty_percentage": 5,
      "cost_per_unit": 76.7
    }
  },
  {
    "id": "vata_vighnaka_gawandha",
    "title": "Vata-Vighnaka Mobile-Joint Compound",
    "description": "Clean §3(e) and legal spread, but Ashwagandha at 48% trips the 45% sedation ceiling — the flagship dose is one slider away from a warning.",
    "target_tier": "siddha",
    "ingredients": [
      {
        "herb_id": "ashwagandha",
        "ratio": 48
      },
      {
        "herb_id": "shallaki",
        "ratio": 15
      },
      {
        "herb_id": "ghee",
        "ratio": 20
      },
      {
        "herb_id": "pippali",
        "ratio": 7
      },
      {
        "herb_id": "vidari",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "ashwagandha": 48,
      "shallaki": 15,
      "ghee": 20,
      "pippali": 7,
      "vidari": 10
    },
    "computed": {
      "quality": 86,
      "ci": 0.65,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 68,
      "tier": "siddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "arsha_kasisa_purva",
    "title": "Arsha Astringent Pre-Kasisa Compound",
    "description": "Triphala-anchored piles formula, but Dantaka at 10% exceeds its 8% plumbagin ceiling — one narrow-window herb blocks export.",
    "target_tier": "vriddha",
    "ingredients": [
      {
        "herb_id": "dantaka",
        "ratio": 10
      },
      {
        "herb_id": "guduchi",
        "ratio": 20
      },
      {
        "herb_id": "amla",
        "ratio": 25
      },
      {
        "herb_id": "haritaki",
        "ratio": 10
      },
      {
        "herb_id": "bibhitaki",
        "ratio": 10
      },
      {
        "herb_id": "ghee",
        "ratio": 10
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      },
      {
        "herb_id": "musta",
        "ratio": 10
      }
    ],
    "baseline_ratios": {
      "dantaka": 10,
      "guduchi": 20,
      "amla": 25,
      "haritaki": 10,
      "bibhitaki": 10,
      "ghee": 10,
      "pippali": 5,
      "musta": 10
    },
    "computed": {
      "quality": 76,
      "ci": 0.81,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "vriddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "hridaya_arjuna_tonic",
    "title": "Hridya Arjuna Cardiac Tonic",
    "description": "Solid carrier-plus-enhancer base, but Arjuna bark at 35% overshoots the 30% API ceiling for prolonged use.",
    "target_tier": "vriddha",
    "ingredients": [
      {
        "herb_id": "arjuna",
        "ratio": 35
      },
      {
        "herb_id": "ashwagandha",
        "ratio": 20
      },
      {
        "herb_id": "shankhpushpi",
        "ratio": 25
      },
      {
        "herb_id": "ghee",
        "ratio": 15
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      }
    ],
    "baseline_ratios": {
      "arjuna": 35,
      "ashwagandha": 20,
      "shankhpushpi": 25,
      "ghee": 15,
      "pippali": 5
    },
    "computed": {
      "quality": 79,
      "ci": 0.71,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "vriddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "bilva_sangraha_sthapana",
    "title": "Grahani Bowel-Stabilising Bilva Build",
    "description": "Balanced cooling bowel yoga, but Bilva at 30% is above the 25% marmin ceiling — reduce to unlock export.",
    "target_tier": "vriddha",
    "ingredients": [
      {
        "herb_id": "bilva",
        "ratio": 30
      },
      {
        "herb_id": "methi",
        "ratio": 20
      },
      {
        "herb_id": "gokshura",
        "ratio": 15
      },
      {
        "herb_id": "musta",
        "ratio": 10
      },
      {
        "herb_id": "ghee",
        "ratio": 15
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      },
      {
        "herb_id": "amla",
        "ratio": 5
      }
    ],
    "baseline_ratios": {
      "bilva": 30,
      "methi": 20,
      "gokshura": 15,
      "musta": 10,
      "ghee": 15,
      "pippali": 5,
      "amla": 5
    },
    "computed": {
      "quality": 73,
      "ci": 0.89,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "vriddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "shukrali_vidari_balya",
    "title": "Shukrali Vidari-Nourish Balya",
    "description": "Three hero adaptogens with full carrier layer; the weak spot is economics — Vidari sourcing pushes procurement cost, not legality.",
    "target_tier": "vriddha",
    "ingredients": [
      {
        "herb_id": "vidari",
        "ratio": 30
      },
      {
        "herb_id": "shatavari",
        "ratio": 30
      },
      {
        "herb_id": "ashwagandha",
        "ratio": 25
      },
      {
        "herb_id": "ghee",
        "ratio": 10
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      }
    ],
    "baseline_ratios": {
      "vidari": 30,
      "shatavari": 30,
      "ashwagandha": 25,
      "ghee": 10,
      "pippali": 5
    },
    "computed": {
      "quality": 79,
      "ci": 0.71,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "vriddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  },
  {
    "id": "chyawan_prasha_minimal",
    "title": "Chyawanprash Minimal Base (Amla-Led)",
    "description": "Amla-heavy classical anchor, but the actives are diffuse: quality lands NOVEL-but-DEFICIENT without a standardized hero extract.",
    "target_tier": "siddha",
    "ingredients": [
      {
        "herb_id": "amla",
        "ratio": 42
      },
      {
        "herb_id": "ashwagandha",
        "ratio": 15
      },
      {
        "herb_id": "guduchi",
        "ratio": 15
      },
      {
        "herb_id": "shankhpushpi",
        "ratio": 8
      },
      {
        "herb_id": "ghee",
        "ratio": 15
      },
      {
        "herb_id": "pippali",
        "ratio": 5
      }
    ],
    "baseline_ratios": {
      "amla": 42,
      "ashwagandha": 15,
      "guduchi": 15,
      "shankhpushpi": 8,
      "ghee": 15,
      "pippali": 5
    },
    "computed": {
      "quality": 83,
      "ci": 0.63,
      "sec_3e_status": "CLEARED",
      "tkdl_concordance_score": 75,
      "tier": "siddha",
      "nba_abs_royalty_percentage": 3,
      "cost_per_unit": 73.9
    }
  }
];
